### ISSUE TITLE
delete method in /app/views.py of v0.8 missing "form = TodoForm()"

### ISSUE THREAD

**Issue by LeonSin** [defshine/awesome-flask-todo#1]
Well , it seems that https://github.com/defshine/awesome-flask-todo/blob/v0.8/app/views.py makes a mistake.when I tried to delete a to-do, error occured. Stack info shows that "form not defined".

PS: Great thanks for your Flask Tutorial. It is an enlighted experience for me to read and take practices. Go on and have a good weekend!

**Comment by defshine** [comment]
Really a mistake,Thank you~
It have been fixed in v0.9, so you can go on learn it
I prepare to leave this small mistake in v0.8
So glad to hear that

**Comment by LeonSin** [comment]
Thanks!
